### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by marcolago**

### CODE REVIEW

**Comment by marcolago** [comment]
Hi. Do you have feedback about the pull request for the Italian translation?
There are errors or something missing?

Thanks

**Comment by DeviPotato** [comment]
Hello!

I'm very sorry for the delay. I took an unplanned hiatus from this project for personal reasons and just started work on it again a few days ago. I am working through all of the things I am behind on now.

Thank you for this contribution and for your work. I don't see any errors that I know about, so I should be able to use it. I'll test it out later today, and merge this if everything looks OK.

I still need to add the Italian weapon names, but I should be able to have that done tomorrow. I'll try to have this on the site in the next day or two.

Thank you for being patient!

**Comment by marcolago** [comment]
No problem.
I've noticed the update on the project so I asked ;)

Thanks for your effort.
This is super useful.

**Comment by DeviPotato** [comment]
Just pulled this in (including your new tweaks from today). Planning to make this live with the next update that goes live. :)

Thank you again for your contribution!

**Pull request merged**
