### PR TITLE
Splatoony UI Update

### PR DESCRIPTION
**Pull request by lah7**
First of all, thanks for making this tool! It's really good and will come handy when I eventually use it _properly_.

I've made some visual changes to enhance the experience and make it mimic more of Splatoon 2's _splatiness_ of a user Interface.

## Dialogs - Before
GIF showing animations before these changes

## Dialogs - After
GIF showing animations in this pull request

## In addition:

* The dropdown for selecting a language is less like Bootstrap's default.
    Screenshot of new dropdown

* Styling has been added to scrollbars for WebKit-based browsers (i.e. Chrome/Safari)
    Scroll bar in a modal dialog Scroll bar in main area

PS. I noticed I was working on ver 1.1.1, but the [loadout.ink](https://loadout.ink) website is on ver 1.1.2. :confused:

Hope you like it! :smile:

### CODE REVIEW

**Comment by lah7** [comment]
Also added another little touch - this one primarily aimed to improve integration on Android.

Before, clicking "Add to Home Screen" would use the favicon (which is hard to see on dark backgrounds) and the text in the `<title>`.

Screenshot of home screen

Now, there is a manifest with a set of icons and gives the short name "loadout.ink". It also helps integrate the website like a web app on the user's device:

Screenshot of window switcher

**Comment by DeviPotato** [comment]
Hey, finally got around to checking this. This is stellar work! I really like it, I'll pull and publish this when I have a moment (hopefully within the next few days).

I'd like to credit you for your contribution in the about dialog if you'd be okay with this!

**Comment by lah7** [comment]
Booyah! :smiley:

I'd be happy with that, thank you -- you can call me @lah7, or my full name (whichever seems to fit best), linking to my [GitHub page](https://github.com/lah7). :+1:

**Comment by frozenpandaman** [comment]
holy

**Pull request merged**
